name: Deploy Plugin

on:
  push:
    branches:
      - main
      - staging
      - release
  workflow_dispatch: # Allows manual triggers as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set deployment path
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/release" ]]; then
            echo "DEPLOY_PATH=${{ secrets.TIGER_GRADES_PATH }}/release/wp-content/plugins/tiger-grades/" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "DEPLOY_PATH=${{ secrets.TIGER_GRADES_PATH }}/staging/wp-content/plugins/tiger-grades/" >> $GITHUB_ENV
          else
            echo "DEPLOY_PATH=${{ secrets.TIGER_GRADES_PATH }}/wp-content/plugins/tiger-grades/" >> $GITHUB_ENV
          fi

      - name: Deploy via Rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: src/
          remote_path: ${{ env.DEPLOY_PATH }}
          remote_host: ${{ secrets.HOSTINGER_HOST }}
          remote_user: ${{ secrets.HOSTINGER_USERNAME }}
          remote_key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          remote_port: ${{ secrets.HOSTINGER_PORT }}

      - name: Clear Cache
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            wp cache flush --path=${{ env.DEPLOY_PATH }}
            wp transient delete --all --path=${{ env.DEPLOY_PATH }}
            wp rewrite flush --hard --path=${{ env.DEPLOY_PATH }}
            # Check if LiteSpeed Cache plugin is active before attempting to purge
            if wp plugin is-active litespeed-cache --path=${{ env.DEPLOY_PATH }}; then
              wp litespeed-purge all --path=${{ env.DEPLOY_PATH }}
            fi

